CREATE TABLE NongSimMember(
	id VARCHAR2(100) PRIMARY KEY,
	password VARCHAR2(100) NOT NULL,
	name VARCHAR2(100) NOT NULL,
	address VARCHAR2(100) NOT NULL,
	nickName VARCHAR2(100) NOT NULL,
	tel VARCHAR2(100) NOT NULL,
	sellerInfo VARCHAR2(100) NOT NULL,
	adminINfo VARCHAR2(100) NOT NULL,
	email VARCHAR2(100) NOT NULL,
	point NUMBER DEFAULT 0,
	accountNo VARCHAR2(100)	
)

CREATE TABLE NongSimProductInfo(
	productNO NUMBER PRIMARY KEY,
	productName VARCHAR2(100) NOT NULL,
	productPoint NUMBER NOT NULL,
	minimumPerson NUMBER NOT NULL,
	duration DATE NOT NULL,
	category VARCHAR2(100) NOT NULL,
	maxPerson NUMBER NOT NULL
)